// Autogenerated Scheme to C++ Code
// File: P3-8.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object sum(Object L){
	Object __RetVal;
	if ((nullp (L))){
	  __RetVal = Object(0);	
}
	
else {
  __RetVal = (listop ("car", L) + 	(__RetVal = sum(listop ("cdr", L))));	}
;
	return __RetVal;
}
int main (){
	Object __RetVal;
	Object l1 = Object("(3 5 )");
	Object l2 = Object("(13 3.5 4 7.8 12 5 )");

	cout << 	(__RetVal = sum(l1));
;
	cout << endl;
	cout << 	(__RetVal = sum(l2));
;
	cout << endl;
	cout << 	(__RetVal = sum(listop ("append", l1, l2)));
;
	cout << endl;
;
	return 0;
}
